spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:6033/app-apontamento
    username: root
    password: my_secret_password
  jpa:
     hibernate:
       ddl-auto: update
       show-sql: false
